import React from 'react';
import type { Metadata } from "next";
import Courselist from './Components/Courselist';

export const metadata: Metadata = {
  title: "Coursezone Project",
  description: "Generated by create next app",
};



const page = () => {
  return (
    <div>
      <Courselist/>
    </div>
  );
}

export default page;
